language: python
python: 3.7.3
dist: xenial
sudo: true

cache: pip

install:
    - pip install -r ./requirements.txt

script:
    - ./CsvGen.py
    - ./GbtxMemLongestPattern.py 20190417
    - cd ./test
    - ./GbtxMemAnalyzer.unittest.py
    - ./GbtxMemParser.unittest.py
    - ./CsvParser.unittest.py
